image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      if [ "$GITPOD_HEADLESS" = "true" ]; then
        # force non-interactive terminal in prebuilds
        export TERM=dumb
      fi

      # disable Gradle auto-reload in IntelliJ
      if [ -f ".idea/workspace.xml" ]; then
          xmlstarlet ed --inplace -u '//option[@name="autoReloadType"]/@value' -v 'NONE' .idea/workspace.xml
      else
          mkdir -p .idea
          cat > .idea/workspace.xml <<EOL
      <?xml version="1.0" encoding="UTF-8"?>
      <project version="4">
          <component name="AutoImportSettings">
              <option name="autoReloadType" value="NONE" />
          </component>
      </project>
      EOL
      fi

      # run standard gradle build
      ./gradlew localDistro

    command: |
      # re-enable Gradle auto-reload in IntelliJ
      xmlstarlet ed --inplace -u '//option[@name="autoReloadType"]/@value' -v 'SELECTIVE' .idea/workspace.xml

jetbrains:
  intellij:
    prebuilds:
      version: stable

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - eamodio.gitlens
