image:
  file: .gitpod.Dockerfile

tasks:
- name: Init cluster workspace
  before: |
    mkdir -p /workspace/.gradle
    printf "org.gradle.jvmargs=-Xmx6g\norg.gradle.daemon=true\n" > /workspace/.gradle/gradle.properties
  # init: |
  #   ./gradlew compileAll -PfetchGwt
  #   ./gradlew ideImport
  #   cd ui/angular/angular.server && yarn install; cd -
  init: |
    if [[ "$GITPOD_HEADLESS" != "true" ]]; then echo "No prebuild, skipping init task."; fi
    ./gradlew compileAll localDistro

jetbrains:
  intellij:
    vmoptions: '-Xmx8g'
    prebuilds:
      version: stable
    plugins:
      - CheckStyle-IDEA
      - intellij.prettierJS
      - org.sonarlint.idea
      - EclipseCodeFormatter
