
image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # force non-interactive terminal
      export TERM=

      touch /workspace/starttime.txt

      # run standard gradle build
      ./gradlew localDistro

      find / -xdev -type f -newer /workspace/starttime.txt > /workspace/lostfiles_$(date +"%Y%m%d_%H%M%S").txt

jetbrains:
  intellij:
    prebuilds:
      version: stable

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - eamodio.gitlens
