image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      #!/bin/bash

      echo "Waiting for Gradle daemon to start..."
      while ! gradle --status 2>/dev/null | grep -q "PID"; do
        sleep 1
        echo "Waiting..."
      done
      echo "Gradle daemon is running."

      while true; do
        if gradle --status 2>/dev/null | grep -q "BUSY"; then
            sleep 1
        else
            echo "Gradle daemon is free. Monitoring for 10 seconds..."
            is_free_for_10_seconds=true
            for ((i=0; i<10; i++)); do
                if gradle --status 2>/dev/null | grep -q "BUSY"; then
                    is_free_for_10_seconds=false
                    break
                fi
                sleep 1
            done
            if [ "$is_free_for_10_seconds" = true ]; then
                break
            fi
        fi
      done

      echo "Gradle daemon is free. Running build..."
      ./gradlew localDistro

jetbrains:
  intellij:
    prebuilds:
      version: stable
