image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      if [ "$GITPOD_HEADLESS" = "true" ]; then
        # force non-interactive terminal in prebuilds
        export TERM=dumb
      fi

      # disable Gradle auto-reload in IntelliJ
      xmlstarlet ed --inplace -u '//option[@name="autoReloadType"]/@value' -v 'NONE' .idea/workspace.xml

      # run standard gradle build
      ./gradlew localDistro

    command: |
      # re-enable Gradle auto-reload in IntelliJ
      xmlstarlet ed --inplace -u '//option[@name="autoReloadType"]/@value' -v 'SELECTIVE' .idea/workspace.xml

jetbrains:
  intellij:
    prebuilds:
      version: stable

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - eamodio.gitlens
