image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sleep 120
      ./gradlew -d localDistro | grep -i daemon > daemon-debug-log.txt

jetbrains:
  intellij:
    prebuilds:
      version: stable
