
image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # force non-interactive terminal
      export TERM=

      touch /workspace/starttime.txt

      # run standard gradle build
      ./gradlew localDistro

      find / -type f -newer /workspace/starttime.txt -xdev > /workspace/lostfiles.txt

jetbrains:
  intellij:
    prebuilds:
      version: stable

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - eamodio.gitlens
