image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # configure Gradle and start tracing scripts
      mkdir -p /workspace/.gradle
      printf "org.gradle.jvmargs=-Xmx6g\norg.gradle.daemon=true\norg.gradle.parallel=true\n" > /workspace/.gradle/gradle.properties
      mkdir -p /workspace/jvm_debug
      nohup ./tracer.sh > /workspace/jvm_debug/tracer.log 2>&1 &
      nohup ./record.sh > /workspace/jvm_debug/record.log 2>&1 &
      nohup ./timeout.sh> /workspace/jvm_debug/timeout.log 2>&1 &
      
      # run the project's build
      ./gradlew localDistro

jetbrains:
  intellij:
    # vmoptions: '-Xmx8g -XX:+UnlockDiagnosticVMOptions -XX:ErrorFile=/workspace/.gitpod/hs_err_pid%p.log -XX:+ExtensiveErrorReports -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/workspace/.gitpod/java_pid%p.hprof'
    prebuilds:
      version: stable
